name: Generate Assembly PDF on every push for test

on:
  push:
    branches:
      - '**'      # Runs on every branch push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Create Outputdir
        run: mkdir -p output 
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Grip
        run: pip install grip
        
      - name: Generate PDF from Markdown
        run: pandoc docs/v2/Assembly.md -o output/Assembly.pdf
      
      - name: Grip Generate PDF from Markdown
        run: grip docs/v2/Assembly.md --export output/Assembly.html
        
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Assembly-PDF
          path: output/*
